### ISSUE TITLE
KITTI annotation issue

### ISSUE THREAD

**Issue by sunggukcha** [vita-epfl/looking#2]
Hello there, 

According to https://looking-vita-epfl.github.io/dataset/ KITTI Training data and Testing data description, 
trainset and testset are to be named `KITTI/train` and `KITTI/test` respectively,
while the annotation file requires the sets to be named `Kitti/Train` and `Kitti/Test`.

It is minor, but might help in the next time.

**Comment by younesbelkada** [comment]
Hi!

Thank you for your message and for pointing out this issue. I think you might face this problem only when you go for the "Manual download" which is deprecated and will be removed soon. Please download the dataset following the instructions on "Automatic download", I will update the website accordingly 

Thanks!
