### ISSUE TITLE
Unable to install openpifpaf=0.13.0

### ISSUE THREAD

**Issue by Matus-Tanonwong** [vita-epfl/looking#4]
Hello!!
I have been trying to install the openpifpaf=0.13.0 on a conda environment but getting the following error:

Building wheel for openpifpaf (PEP 517) ... error                                                                                                            
ERROR: Failed building wheel for openpifpaf                                                                                                                                              Failed to build openpifpaf                                                                                           
ERROR: Could not build wheels for openpifpaf which use PEP 517 and cannot be installed directly
  
Here are my current dependencies:
Ubuntu 18.04
CUDA 10.2
conda 4.11.0
Python 3.8.12
torch 1.10.2
torch vision 0.11.3

Could anyone please guide me on how to fix this issue?

**Comment by younesbelkada** [comment]
Hi there,

Thank you very much for your comment!
On my side I have managed to install correctly the requirements using python virtual environment with python version 3.8.10. Could you try to run creating the virtual environment using [```venv```](https://docs.python.org/3/library/venv.html)?
I have also updated the requirements.txt file

Thanks!

**Comment by Matus-Tanonwong** [comment]
Thank you very much for your quick response!

After I created the virtual environment using venv with python 3.8.5, I tried to install the openpifpaf but got a new error as the following:

RuntimeError: Error compiling objects for extension                                                                     [end of output]                                                                                                                                                                                                                             note: This error originates from a subprocess, and is likely not a problem with pip.                                    ERROR: Failed building wheel for openpifpaf                                                                           Failed to build openpifpaf                                                                                              ERROR: Could not build wheels for openpifpaf, which is required to install pyproject.toml-based projects  

Do I specifically need to install it with python version 3.8.10?

**Comment by younesbelkada** [comment]
Hi,

Yes could you please try it with Python 3.8.10 ? 
If it still persists I suspect it is an issue related to your cuda version together with openpifpaf, I suggest you to post the issue on [openpifpaf's official repo](https://github.com/openpifpaf/openpifpaf)
Please let me know, thanks

**Comment by Matus-Tanonwong** [comment]
Thank you very much for your response!

It worked with Python 3.8.10.
